name: 'binaryen wasm-opt'
author: "Niklas Eicker (@NiklasEi), Johannes Deml (@JohannesDeml)"
description: "Use WebAssembly/binaryen's wasm-opt in your workflows"
branding:
  icon: arrow-down-circle
  color: green
inputs:
  file:
    description: 'The wasm file to optimize'
    required: true
  output:
    description: 'The output wasm file'
    required: false
  optimize_all:
    description: 'Set to "true" if you would like to optimize all matching files'
    required: false
  options:
    description: 'Additional options to pass to wasm-opt'
    required: false
  binaryen_version:
    description: 'The minor version of binaryen to use (e.g. 122)'
    required: false
    default: '122'
runs:
  using: 'composite'
  steps:
    - name: Run wasm-opt
      shell: bash
      run: |
        # Change version v1.${{ inputs.binaryen_version }}.1 in the following lines when creating a new version
        docker pull johannesdeml/binaryen-wasm-opt:v1.${{ inputs.binaryen_version }}.1
        docker run --rm -v ${{ github.workspace }}:/github/workspace -w /github/workspace \
          johannesdeml/binaryen-wasm-opt:v1.${{ inputs.binaryen_version }}.1 \
          "${{ inputs.file }}" "${{ inputs.output }}" "${{ inputs.optimize_all }}" "${{ inputs.options }}"
