name: 'wasm-opt action'
author: "Niklas Eicker (@NiklasEi)"
description: "Use WebAssembly/binaryen's wasm-opt in your workflows"
branding:
  icon: arrow-down-circle
  color: blue
inputs:
  file:
    description: 'The wasm file to optimize'
    required: true
  output:
    description: 'The output wasm file'
    required: false
  options:
    description: 'Additional options to pass to wasm-opt'
    required: false
runs:
  using: 'docker'
  image: 'docker://niklasei/wasm-opt-action:v2.1.0'
  args:
    - ${{ inputs.file }}
    - ${{ inputs.output }}
    - ${{ inputs.options }}
