name: 'wasm-opt action'
author: "Niklas Eicker (@NiklasEi), Johannes Deml (@JohannesDeml)"
description: "Use WebAssembly/binaryen's wasm-opt in your workflows"
branding:
  icon: arrow-down-circle
  color: blue
inputs:
  file:
    description: 'The wasm file to optimize'
    required: true
  output:
    description: 'The output wasm file'
    required: false
  optimize_all:
    description: 'Set to "true" if you would like to optimize all matching files'
    required: false
  options:
    description: 'Additional options to pass to wasm-opt'
    required: false
  binaryen_version:
    description: 'The minor version of binaryen to use (e.g. 122)'
    required: false
    default: '122'
runs:
  using: 'docker'
  # The major/patch version needs to be updated when a new version of the action is released
  image: 'docker://johannesdeml/wasm-opt-action:v1.${{ inputs.binaryen_version }}.0'
  args:
    - ${{ inputs.file }}
    - ${{ inputs.output }}
    - ${{ inputs.optimize_all }}
    - ${{ inputs.options }}
