name: Build and Publish Docker Image

on:
  push:
    tags:
      - 'docker-*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version info from tag
        id: version
        run: |
          # Extract version numbers from tag (e.g., docker-1.122.0)
          TAG=${GITHUB_REF#refs/tags/docker-}
          echo "version=$TAG" >> $GITHUB_OUTPUT
          # Extract binaryen version (second number/minor version)
          BINARYEN_VERSION=$(echo $TAG | cut -d'.' -f2)
          echo "binaryen_version=$BINARYEN_VERSION" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            BINARYEN_VERSION=${{ steps.version.outputs.binaryen_version }}
          tags: |
            johannesdeml/wasm-opt-action:v${{ steps.version.outputs.version }}